server:
    songify:
        drawingSpeed: 
            max: 0.8
            min: 0        
        drawingDistance: 
            max: 5
            min: 0        
        drawingSpread: 
            max: 2
            min: 0

    ECHONEST_API_HOST: developer.echonest.com/api/v4
    ECHONEST_API_URL: http://developer.echonest.com/api/v4/